# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ gh_pages ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core and .Net Framework
      uses: microsoft/setup-msbuild@v1.0.1
    - name: Install dependencies
      run: dotnet restore src/UNMealPlanner/UNMealPlanner.sln
    - name: Build
      run: dotnet build src/UNMealPlanner/UNMealPlanner.sln --configuration Release --no-restore
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.6.1
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       BRANCH: gh-pages # The branch the action should deploy to.
       FOLDER: build # The folder the action should deploy.
       CLEAN: true # Automatically remove deleted files from the deploy branch
